// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PhotoData.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace GrpcDefinition {
  public static partial class ContentServer
  {
    static readonly string __ServiceName = "ContentServer";

    static readonly grpc::Marshaller<global::GrpcDefinition.Request> __Marshaller_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcDefinition.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcDefinition.PhotoSetsDataResult> __Marshaller_PhotoSetsDataResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcDefinition.PhotoSetsDataResult.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcDefinition.Request, global::GrpcDefinition.PhotoSetsDataResult> __Method_GetContent_v1 = new grpc::Method<global::GrpcDefinition.Request, global::GrpcDefinition.PhotoSetsDataResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetContent_v1",
        __Marshaller_Request,
        __Marshaller_PhotoSetsDataResult);

    static readonly grpc::Method<global::GrpcDefinition.Request, global::GrpcDefinition.PhotoSetsDataResult> __Method_GetContent_v2 = new grpc::Method<global::GrpcDefinition.Request, global::GrpcDefinition.PhotoSetsDataResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetContent_v2",
        __Marshaller_Request,
        __Marshaller_PhotoSetsDataResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcDefinition.PhotoDataReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ContentServer</summary>
    public abstract partial class ContentServerBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GrpcDefinition.PhotoSetsDataResult> GetContent_v1(global::GrpcDefinition.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::GrpcDefinition.PhotoSetsDataResult> GetContent_v2(global::GrpcDefinition.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ContentServer</summary>
    public partial class ContentServerClient : grpc::ClientBase<ContentServerClient>
    {
      /// <summary>Creates a new client for ContentServer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ContentServerClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ContentServer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ContentServerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ContentServerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ContentServerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GrpcDefinition.PhotoSetsDataResult GetContent_v1(global::GrpcDefinition.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetContent_v1(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcDefinition.PhotoSetsDataResult GetContent_v1(global::GrpcDefinition.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetContent_v1, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcDefinition.PhotoSetsDataResult> GetContent_v1Async(global::GrpcDefinition.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetContent_v1Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcDefinition.PhotoSetsDataResult> GetContent_v1Async(global::GrpcDefinition.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetContent_v1, null, options, request);
      }
      public virtual global::GrpcDefinition.PhotoSetsDataResult GetContent_v2(global::GrpcDefinition.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetContent_v2(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcDefinition.PhotoSetsDataResult GetContent_v2(global::GrpcDefinition.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetContent_v2, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcDefinition.PhotoSetsDataResult> GetContent_v2Async(global::GrpcDefinition.Request request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetContent_v2Async(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcDefinition.PhotoSetsDataResult> GetContent_v2Async(global::GrpcDefinition.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetContent_v2, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ContentServerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ContentServerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ContentServerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetContent_v1, serviceImpl.GetContent_v1)
          .AddMethod(__Method_GetContent_v2, serviceImpl.GetContent_v2).Build();
    }

  }
}
#endregion
